### ISSUE TITLE
Problem installing payslip

### ISSUE THREAD

**Issue by timotme** [tjvr/pyswip#2]
Hello,

I did everything that is told in the INSTALL file and I got this error message.

`>>> from pyswip import Prolog
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pyswip/__init__.py", line 29, in <module>
    from pyswip.prolog import Prolog
  File "/Library/Python/2.7/site-packages/pyswip/prolog.py", line 29, in <module>
    from pyswip.core import *
  File "/Library/Python/2.7/site-packages/pyswip/core.py", line 356, in <module>
    (_path, SWI_HOME_DIR) = _findSwipl()
  File "/Library/Python/2.7/site-packages/pyswip/core.py", line 319, in _findSwipl
    raise ImportError('Could not find the SWI-Prolog library in this '
ImportError: Could not find the SWI-Prolog library in this platform. If you are sure it is installed, please open an issue.

in `/usr/local/lib` I have the two files `libswipl.a` and `libswipl.dylib`.

Do you have any idea why ? 
Thank you in advance.

**Comment by tjvr** [comment]
Sorry, this is just a clone of the Google code repo; this isn't supported.
